"""
ℹ️ About Page
Project information, tech stack, and credits.
"""

import streamlit as st
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

st.set_page_config(
    page_title="About - AI vs Real",
    page_icon="ℹ️",
    layout="wide",
)

from app import inject_custom_css, render_sidebar
inject_custom_css()
render_sidebar()

# ============================================================
# Header
# ============================================================
st.markdown("""
<div class="hero-title" style="font-size: 2.4rem;">ℹ️ About This Project</div>
<div class="hero-subtitle">AI-Generated Image Detection using Deep Learning</div>
""", unsafe_allow_html=True)

st.markdown("---")

# ============================================================
# Project Description
# ============================================================
st.markdown('<div class="section-header">🎯 Project Description</div>', unsafe_allow_html=True)

st.markdown("""
<div class="glass-card">
    <p style="color: #E2E8F0; font-size: 1.05rem; line-height: 1.8;">
        This project implements a comprehensive <strong style="color: #8B5CF6;">AI-Generated Image Detection System</strong> 
        that leverages deep learning, frequency-domain analysis, and metadata inspection to determine 
        whether an uploaded image was captured by a real camera or generated by an AI model.
    </p>
    <br>
    <p style="color: #94A3B8; font-size: 0.95rem; line-height: 1.7;">
        The system can detect images generated by popular AI tools including ChatGPT (DALL-E), 
        Google Gemini, Midjourney, Stable Diffusion, Adobe Firefly, and others. It provides 
        not just a binary classification but also explainable results through Grad-CAM heatmaps, 
        frequency spectrum visualization, and detailed metadata analysis.
    </p>
</div>
""", unsafe_allow_html=True)

# ============================================================
# Technology Stack
# ============================================================
st.markdown('<div class="section-header">⚙️ Technology Stack</div>', unsafe_allow_html=True)

col1, col2 = st.columns(2)

with col1:
    st.markdown("""
    <div class="glass-card">
        <h4 style="color: #8B5CF6;">🧠 AI / ML Stack</h4>
        <table style="width: 100%; color: #E2E8F0; border-collapse: collapse; font-size: 0.9rem;">
            <tr style="border-bottom: 1px solid rgba(139,92,246,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Deep Learning Framework</td>
                <td style="padding: 0.6rem;">TensorFlow 2.x / Keras</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(139,92,246,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Model Architecture</td>
                <td style="padding: 0.6rem;">EfficientNetV2-B0</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(139,92,246,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Training Technique</td>
                <td style="padding: 0.6rem;">Transfer Learning (ImageNet)</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(139,92,246,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Explainability</td>
                <td style="padding: 0.6rem;">Grad-CAM</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(139,92,246,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Signal Processing</td>
                <td style="padding: 0.6rem;">FFT (NumPy, SciPy)</td>
            </tr>
            <tr>
                <td style="padding: 0.6rem; color: #94A3B8;">Metrics</td>
                <td style="padding: 0.6rem;">Scikit-learn</td>
            </tr>
        </table>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown("""
    <div class="glass-card">
        <h4 style="color: #06B6D4;">🖥️ Application Stack</h4>
        <table style="width: 100%; color: #E2E8F0; border-collapse: collapse; font-size: 0.9rem;">
            <tr style="border-bottom: 1px solid rgba(6,182,212,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Web Framework</td>
                <td style="padding: 0.6rem;">Streamlit</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(6,182,212,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Visualization</td>
                <td style="padding: 0.6rem;">Plotly, Matplotlib, Seaborn</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(6,182,212,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Image Processing</td>
                <td style="padding: 0.6rem;">Pillow, OpenCV</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(6,182,212,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Metadata</td>
                <td style="padding: 0.6rem;">PIL EXIF, exifread</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(6,182,212,0.1);">
                <td style="padding: 0.6rem; color: #94A3B8;">Data Handling</td>
                <td style="padding: 0.6rem;">NumPy, Pandas</td>
            </tr>
            <tr>
                <td style="padding: 0.6rem; color: #94A3B8;">Language</td>
                <td style="padding: 0.6rem;">Python 3.10+</td>
            </tr>
        </table>
    </div>
    """, unsafe_allow_html=True)

# ============================================================
# Key Features
# ============================================================
st.markdown('<div class="section-header">✨ Key Features</div>', unsafe_allow_html=True)

features = [
    ("🧠", "Deep Learning Classification", 
     "EfficientNetV2-B0 with transfer learning, achieving 95%+ accuracy"),
    ("📡", "Frequency Domain Analysis", 
     "FFT-based spectral analysis to detect AI generation artifacts"),
    ("📋", "EXIF Metadata Inspection", 
     "Automated analysis of camera metadata and AI software signatures"),
    ("🔥", "Grad-CAM Visualization", 
     "Visual explainability showing model's attention regions"),
    ("📊", "Comprehensive Dashboard", 
     "Training metrics, confusion matrix, ROC curves, and comparisons"),
    ("📥", "Report Export", 
     "Download detailed JSON analysis report for each image"),
]

cols = st.columns(3)
for i, (icon, title, desc) in enumerate(features):
    with cols[i % 3]:
        st.markdown(f"""
        <div class="feature-card">
            <div class="feature-icon">{icon}</div>
            <div class="feature-title">{title}</div>
            <div class="feature-desc">{desc}</div>
        </div>
        """, unsafe_allow_html=True)
        st.markdown("", unsafe_allow_html=True)

# ============================================================
# Project Structure
# ============================================================
st.markdown('<div class="section-header">📁 Project Structure</div>', unsafe_allow_html=True)

st.markdown("""
<div class="glass-card">
<pre style="color: #E2E8F0; font-size: 0.85rem; line-height: 1.6; font-family: 'Fira Code', monospace;">
ai-vs-real-detector/
├── 📄 app.py                        <span style="color: #8B5CF6;"># Main Streamlit application</span>
├── 📄 requirements.txt              <span style="color: #8B5CF6;"># Python dependencies</span>
├── 📄 README.md                     <span style="color: #8B5CF6;"># Project documentation</span>
├── 📁 .streamlit/
│   └── config.toml                  <span style="color: #06B6D4;"># Dark theme configuration</span>
├── 📁 models/
│   ├── train_model.py               <span style="color: #06B6D4;"># Training pipeline script</span>
│   └── saved_model/                 <span style="color: #06B6D4;"># Trained model weights & metrics</span>
├── 📁 utils/
│   ├── image_preprocessing.py       <span style="color: #10B981;"># Image loading & normalization</span>
│   ├── frequency_analysis.py        <span style="color: #10B981;"># FFT spectral analysis</span>
│   ├── metadata_inspector.py        <span style="color: #10B981;"># EXIF metadata extraction</span>
│   └── gradcam.py                   <span style="color: #10B981;"># Grad-CAM visualization</span>
├── 📁 pages/
│   ├── 1_🔍_Detect.py              <span style="color: #F59E0B;"># Main detection interface</span>
│   ├── 2_📊_Model_Performance.py    <span style="color: #F59E0B;"># Metrics dashboard</span>
│   ├── 3_📚_How_It_Works.py        <span style="color: #F59E0B;"># Educational page</span>
│   └── 4_ℹ️_About.py              <span style="color: #F59E0B;"># About & credits</span>
└── 📁 data/
    └── download_dataset.py          <span style="color: #F43F5E;"># Dataset download script</span>
</pre>
</div>
""", unsafe_allow_html=True)

# ============================================================
# References
# ============================================================
st.markdown('<div class="section-header">📚 References</div>', unsafe_allow_html=True)

st.markdown("""
<div class="glass-card">
    <ol style="color: #94A3B8; line-height: 2; font-size: 0.9rem;">
        <li>Bird, J.J. and Lotfi, A. (2024). "CIFAKE: Image Classification and Explainable 
        Identification of AI-Generated Synthetic Images." <em>IEEE Access</em>.</li>
        <li>Tan, M. and Le, Q. (2021). "EfficientNetV2: Smaller Models and Faster Training." 
        <em>ICML 2021</em>.</li>
        <li>Selvaraju, R.R., et al. (2017). "Grad-CAM: Visual Explanations from Deep Networks 
        via Gradient-based Localization." <em>ICCV 2017</em>.</li>
        <li>Wang, S.Y., et al. (2020). "CNN-generated images are surprisingly easy to spot...
        for now." <em>CVPR 2020</em>.</li>
        <li>Corvi, R., et al. (2023). "On the detection of synthetic images generated by 
        diffusion models." <em>ICASSP 2023</em>.</li>
    </ol>
</div>
""", unsafe_allow_html=True)

# ============================================================
# Footer
# ============================================================
st.markdown("---")

st.markdown("""
<div style="text-align: center; padding: 2rem 0;">
    <p style="color: #64748B; font-size: 0.9rem;">
        Built with ❤️ using Python, TensorFlow, and Streamlit
    </p>
    <p style="color: #475569; font-size: 0.8rem;">
        © 2026 AI vs Real Image Detector — University Major Project
    </p>
</div>
""", unsafe_allow_html=True)
